version: '3'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    env_file:
      - ./influx2.env
    restart: always

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./grafana.env
    restart: always

  telegraf:
    image: telegraf:latest
    ports:
      - "8125:8125"
    links:
      - influxdb
    env_file:
      - ./influx2.env
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always

volumes:
  grafana_data:
    external: false

  influxdb_data:
    external: false
